/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_IPRoute */

#ifndef _Included_be_ac_ucl_ingi_cbgp_IPRoute
#define _Included_be_ac_ucl_ingi_cbgp_IPRoute
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_IPRoute_NET_ROUTE_STATIC
#define be_ac_ucl_ingi_cbgp_IPRoute_NET_ROUTE_STATIC 1L
#undef be_ac_ucl_ingi_cbgp_IPRoute_NET_ROUTE_IGP
#define be_ac_ucl_ingi_cbgp_IPRoute_NET_ROUTE_IGP 2L
#undef be_ac_ucl_ingi_cbgp_IPRoute_NET_ROUTE_BGP
#define be_ac_ucl_ingi_cbgp_IPRoute_NET_ROUTE_BGP 4L
#ifdef __cplusplus
}
#endif
#endif
