/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_bgp_Router */

#ifndef _Included_be_ac_ucl_ingi_cbgp_bgp_Router
#define _Included_be_ac_ucl_ingi_cbgp_bgp_Router
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Router
 * Method:    addNetwork
 * Signature: (Ljava/lang/String;)Lbe/ac/ucl/ingi/cbgp/IPPrefix;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Router_addNetwork
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Router
 * Method:    delNetwork
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Router_delNetwork
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Router
 * Method:    addPeer
 * Signature: (Ljava/lang/String;I)Lbe/ac/ucl/ingi/cbgp/bgp/Peer;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Router_addPeer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Router
 * Method:    getPeers
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Router_getPeers
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Router
 * Method:    getNetworks
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Router_getNetworks
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Router
 * Method:    getRIB
 * Signature: (Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Router_getRIB
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
