/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_bgp_Filter */

#ifndef _Included_be_ac_ucl_ingi_cbgp_bgp_Filter
#define _Included_be_ac_ucl_ingi_cbgp_bgp_Filter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Filter
 * Method:    getRules
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Filter_getRules
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
