/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_ProxyObject */

#ifndef _Included_be_ac_ucl_ingi_cbgp_ProxyObject
#define _Included_be_ac_ucl_ingi_cbgp_ProxyObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_ac_ucl_ingi_cbgp_ProxyObject
 * Method:    _jni_unregister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_ProxyObject__1jni_1unregister
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
