/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_AbstractConsoleEventListener */

#ifndef _Included_be_ac_ucl_ingi_cbgp_AbstractConsoleEventListener
#define _Included_be_ac_ucl_ingi_cbgp_AbstractConsoleEventListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
