/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_CBGPException */

#ifndef _Included_be_ac_ucl_ingi_cbgp_CBGPException
#define _Included_be_ac_ucl_ingi_cbgp_CBGPException
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_CBGPException_serialVersionUID
#define be_ac_ucl_ingi_cbgp_CBGPException_serialVersionUID -3042686055658047285LL
#undef be_ac_ucl_ingi_cbgp_CBGPException_serialVersionUID
#define be_ac_ucl_ingi_cbgp_CBGPException_serialVersionUID -3387516993124229948LL
#undef be_ac_ucl_ingi_cbgp_CBGPException_serialVersionUID
#define be_ac_ucl_ingi_cbgp_CBGPException_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
