/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_bgp_ASPathSegment */

#ifndef _Included_be_ac_ucl_ingi_cbgp_bgp_ASPathSegment
#define _Included_be_ac_ucl_ingi_cbgp_bgp_ASPathSegment
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_bgp_ASPathSegment_AS_PATH_SEGMENT_SET
#define be_ac_ucl_ingi_cbgp_bgp_ASPathSegment_AS_PATH_SEGMENT_SET 1L
#undef be_ac_ucl_ingi_cbgp_bgp_ASPathSegment_AS_PATH_SEGMENT_SEQUENCE
#define be_ac_ucl_ingi_cbgp_bgp_ASPathSegment_AS_PATH_SEGMENT_SEQUENCE 2L
#ifdef __cplusplus
}
#endif
#endif
