/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_IPTrace */

#ifndef _Included_be_ac_ucl_ingi_cbgp_IPTrace
#define _Included_be_ac_ucl_ingi_cbgp_IPTrace
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_SUCCESS
#define be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_SUCCESS 0L
#undef be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_TOO_LONG
#define be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_TOO_LONG -1L
#undef be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_UNREACH
#define be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_UNREACH -2L
#undef be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_DOWN
#define be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_DOWN -3L
#undef be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_TUNNEL_UNREACH
#define be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_TUNNEL_UNREACH -4L
#undef be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_TUNNEL_BROKEN
#define be_ac_ucl_ingi_cbgp_IPTrace_IP_TRACE_TUNNEL_BROKEN -5L
#ifdef __cplusplus
}
#endif
#endif
