/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_net_IGPDomain */

#ifndef _Included_be_ac_ucl_ingi_cbgp_net_IGPDomain
#define _Included_be_ac_ucl_ingi_cbgp_net_IGPDomain
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_net_IGPDomain_DOMAIN_IGP
#define be_ac_ucl_ingi_cbgp_net_IGPDomain_DOMAIN_IGP 0L
#undef be_ac_ucl_ingi_cbgp_net_IGPDomain_DOMAIN_OSPF
#define be_ac_ucl_ingi_cbgp_net_IGPDomain_DOMAIN_OSPF 1L
/*
 * Class:     be_ac_ucl_ingi_cbgp_net_IGPDomain
 * Method:    addNode
 * Signature: (Ljava/lang/String;)Lbe/ac/ucl/ingi/cbgp/net/Node;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_net_IGPDomain_addNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_net_IGPDomain
 * Method:    getNodes
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_net_IGPDomain_getNodes
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_net_IGPDomain
 * Method:    compute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_net_IGPDomain_compute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
