/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_bgp_Peer */

#ifndef _Included_be_ac_ucl_ingi_cbgp_bgp_Peer
#define _Included_be_ac_ucl_ingi_cbgp_bgp_Peer
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_IDLE
#define be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_IDLE 0L
#undef be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_OPENWAIT
#define be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_OPENWAIT 1L
#undef be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_ESTABLISHED
#define be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_ESTABLISHED 2L
#undef be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_ACTIVE
#define be_ac_ucl_ingi_cbgp_bgp_Peer_SESSION_STATE_ACTIVE 3L
#undef be_ac_ucl_ingi_cbgp_bgp_Peer_PEER_FLAG_RR_CLIENT
#define be_ac_ucl_ingi_cbgp_bgp_Peer_PEER_FLAG_RR_CLIENT 1L
#undef be_ac_ucl_ingi_cbgp_bgp_Peer_PEER_FLAG_VIRTUAL
#define be_ac_ucl_ingi_cbgp_bgp_Peer_PEER_FLAG_VIRTUAL 4L
#undef be_ac_ucl_ingi_cbgp_bgp_Peer_PEER_FLAG_SOFT_RESTART
#define be_ac_ucl_ingi_cbgp_bgp_Peer_PEER_FLAG_SOFT_RESTART 8L
/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    getRouterID
 * Signature: ()Lbe/ac/ucl/ingi/cbgp/IPAddress;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_getRouterID
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    getSessionState
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_getSessionState
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    openSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_openSession
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    closeSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_closeSession
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    bgpRouterPeerRecv
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_bgpRouterPeerRecv
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    getAdjRib
 * Signature: (Ljava/lang/String;Z)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_getAdjRib
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    getFlags
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    isInternal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_isInternal
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    getNextHopSelf
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_getNextHopSelf
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    setNextHopSelf
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_setNextHopSelf
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    getInputFilter
 * Signature: ()Lbe/ac/ucl/ingi/cbgp/bgp/Filter;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_getInputFilter
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Peer
 * Method:    getOutputFilter
 * Signature: ()Lbe/ac/ucl/ingi/cbgp/bgp/Filter;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Peer_getOutputFilter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
