/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_bgp_Message */

#ifndef _Included_be_ac_ucl_ingi_cbgp_bgp_Message
#define _Included_be_ac_ucl_ingi_cbgp_bgp_Message
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_bgp_Message_TYPE_UPDATE
#define be_ac_ucl_ingi_cbgp_bgp_Message_TYPE_UPDATE 0L
#undef be_ac_ucl_ingi_cbgp_bgp_Message_TYPE_WITHDRAW
#define be_ac_ucl_ingi_cbgp_bgp_Message_TYPE_WITHDRAW 1L
#ifdef __cplusplus
}
#endif
#endif
