/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_bgp_Route */

#ifndef _Included_be_ac_ucl_ingi_cbgp_bgp_Route
#define _Included_be_ac_ucl_ingi_cbgp_bgp_Route
#ifdef __cplusplus
extern "C" {
#endif
#undef be_ac_ucl_ingi_cbgp_bgp_Route_ROUTE_ORIGIN_IGP
#define be_ac_ucl_ingi_cbgp_bgp_Route_ROUTE_ORIGIN_IGP 0L
#undef be_ac_ucl_ingi_cbgp_bgp_Route_ROUTE_ORIGIN_EGP
#define be_ac_ucl_ingi_cbgp_bgp_Route_ROUTE_ORIGIN_EGP 1L
#undef be_ac_ucl_ingi_cbgp_bgp_Route_ROUTE_ORIGIN_INCOMPLETE
#define be_ac_ucl_ingi_cbgp_bgp_Route_ROUTE_ORIGIN_INCOMPLETE 2L
#ifdef __cplusplus
}
#endif
#endif
