/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_CBGP */

#ifndef _Included_be_ac_ucl_ingi_cbgp_CBGP
#define _Included_be_ac_ucl_ingi_cbgp_CBGP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_destroy
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netAddNode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netAddNode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netAddLink
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netAddLink
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netLinkWeight
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netLinkWeight
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netLinkUp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netLinkUp
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netNodeSpfPrefix
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netNodeSpfPrefix
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netNodeRouteAdd
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netNodeRouteAdd
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netNodeGetLinks
 * Signature: (Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netNodeGetLinks
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    netNodeGetRT
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_netNodeGetRT
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpAddRouter
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpAddRouter
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterAddNetwork
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterAddNetwork
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterAddPeer
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterAddPeer
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterPeerNextHopSelf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterPeerNextHopSelf
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterPeerVirtual
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterPeerVirtual
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterPeerUp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterPeerUp
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterPeerRecv
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterPeerRecv
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterRescan
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterRescan
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterGetPeers
 * Signature: (Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterGetPeers
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterGetRib
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterGetRib
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterGetAdjRib
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterGetAdjRib
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    bgpRouterLoadRib
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_bgpRouterLoadRib
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    simRun
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_simRun
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     be_ac_ucl_ingi_cbgp_CBGP
 * Method:    runCmd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_be_ac_ucl_ingi_cbgp_CBGP_runCmd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
