/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_ConsoleEvent */

#ifndef _Included_be_ac_ucl_ingi_cbgp_ConsoleEvent
#define _Included_be_ac_ucl_ingi_cbgp_ConsoleEvent
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
