/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_ac_ucl_ingi_cbgp_bgp_Domain */

#ifndef _Included_be_ac_ucl_ingi_cbgp_bgp_Domain
#define _Included_be_ac_ucl_ingi_cbgp_bgp_Domain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Domain
 * Method:    getRouters
 * Signature: ()Ljava/util/Vector;
 */
JNIEXPORT jobject JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Domain_getRouters
  (JNIEnv *, jobject);

/*
 * Class:     be_ac_ucl_ingi_cbgp_bgp_Domain
 * Method:    rescan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_ac_ucl_ingi_cbgp_bgp_Domain_rescan
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
